project_name: falcoctl
before:
  hooks:
    - go mod tidy

builds:
  - id: "falcoctl"
    goos:
    - linux
    - darwin
    - windows
    goarch:
    - amd64
    - 386
    - arm64
    ignore:
    - goos: darwin
      goarch: 386

    ldflags: |
      -X github.com/falcosecurity/falcoctl/pkg/version.buildDate={{ .Date }}
      -X github.com/falcosecurity/falcoctl/pkg/version.gitCommit={{ .Commit }}
      -X github.com/falcosecurity/falcoctl/pkg/version.semVersion={{ if .IsSnapshot }}{{ .Commit }}{{ else }}{{ .Version }}{{ end }}
    main: .
    env:
      - GO111MODULE=on
      - CGO_ENABLED=0

archives:
  - id: windows
    format_overrides:
      - goos: windows
        format: zip

snapshot:
  name_template: "{{ .ShortCommit }}"

release:
  github:
  prerelease: auto
  mode: replace

changelog:
  use: github
