name: docker-image

on:
  workflow_call:
    inputs:
      release:
        required: true
        type: string
      commit:
        required: true
        type: string
      build_date:
        required: true
        type: string
      sign:
        required: false
        default: false
        type: boolean
    outputs:
      digest:
        description: The digest of the pushed image.
        value: ${{ jobs.docker-image.outputs.digest }}

permissions:
  contents: read
  id-token: write

jobs:
  docker-image:
    runs-on: ubuntu-22.04
    outputs:
      image: ${{ steps.build-and-push.outputs.image }}
      digest: ${{ steps.build-and-push.outputs.digest }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4.1.0

      - name: Set up Docker Buildx
        id: Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0

      - name: Login to Docker Hub
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_SECRET }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@99214aa6889fcddfa57764031d71add364327e59 # v6.1.3
        with:
          role-to-assume: arn:aws:iam::292999226676:role/github_actions-falcoctl-ecr
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@fa648b43de3d4d023bcb3f89ed6940096949c419 # v2.1.5
        with:
          registry-type: public

      - name: Docker Meta
        id: meta_falcoctl
        uses: docker/metadata-action@80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9 # v6.1.0
        with:
          # list of Docker images to use as base name for tags
          images: |
            docker.io/falcosecurity/falcoctl
            public.ecr.aws/falcosecurity/falcoctl
          tags: |
            type=ref,event=branch
            type=semver,pattern={{ version }}
            type=semver,pattern={{ major }}
            type=semver,pattern={{ major }}.{{ minor }}

      - name: Build and push
        id: build-and-push
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta_falcoctl.outputs.tags }}
          file: ./build/Dockerfile
          build-args: |
            RELEASE=${{ inputs.release }}
            COMMIT=${{ inputs.commit }}
            BUILD_DATE=${{ inputs.build_date }}

      - name: Install Cosign
        if: ${{ inputs.sign }}
        uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6 # v4.1.2

      - name: Sign the images with GitHub OIDC Token
        if: ${{ inputs.sign }}
        env:
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
          TAGS: ${{ steps.meta_falcoctl.outputs.tags }}
          COSIGN_YES: "true"
        run: echo "${TAGS}" | xargs -I {} cosign sign {}@${DIGEST}
