name: Falcoctl CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go 1.17
      uses: actions/setup-go@v3
      with:
        go-version: 1.17.x
    - name: Checkout Go
      uses: actions/checkout@v3
    - run: make

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go 1.17 
      uses: actions/setup-go@v3
      with:
        go-version: 1.17.x
    - name: Checkout Go 
      uses: actions/checkout@v3
    - run: make test