name: Linting
on:
  pull_request:

jobs:
  golangci:
    name: Lint golang files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: "go.mod"
          check-latest: true
          cache: "false"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@82606bf257cbaff209d206a39f5134f0cfbfd2ee # v9.2.1
        with:
          only-new-issues: true
          version: v2.11.4
          args: --timeout=900s

  gomodtidy:
    name: Enforce go.mod tidiness
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: "${{ github.event.pull_request.head.sha }}"
          repository: ${{github.event.pull_request.head.repo.full_name}}
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: "go.mod"
          check-latest: true

      - name: Execute go mod tidy and check the outcome
        working-directory: ./
        run: |
          go mod tidy
          exit_code=$(git diff --exit-code)
          exit ${exit_code}

      - name: Print a comment in case of failure
        run: |
          echo "The go.mod and/or go.sum files appear not to be correctly tidied.

          Please, rerun go mod tidy to fix the issues."
          exit 1
        if: |
          failure() && github.event.pull_request.head.repo.full_name == github.repository
